 Applying consultant_app.0004_auto_20161209_1017...Traceback (most recent call last):
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: malformed array literal: "to do for admin"
DETAIL:  Array value must start with "{" or dimension information.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 482, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/backends/postgresql/schema.py", line 110, in _alter_field
    new_db_params, strict,
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 634, in _alter_field
    params,
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/consultadd/Desktop/workspace/tixdo_space/tix_env/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: malformed array literal: "to do for admin"
DETAIL:  Array value must start with "{" or dimension information.

(tix_env) consultadd@consultadd-All-Series:~/Desktop/workspace/tixdo_space/uttu_project/my_project$ 

